const SEAT_TYPE = {
    EMPTY: "empty",
    NORMAL: "normal",
    VIP: "vip",
    DOUBLE: "double",
};

const PRICE = {
    EMPTY: 0,
    NORMAL: 50,
    VIP: 70,
    DOUBLE: 100,
};

module.exports = [
    {
        id: 1,
        name: "F01",
        seatConfigs: [
            {
                type: SEAT_TYPE.NORMAL,
                price: PRICE.NORMAL,
            },
            {
                type: SEAT_TYPE.VIP,
                price: PRICE.VIP,
            },
            {
                type: SEAT_TYPE.DOUBLE,
                price: PRICE.DOUBLE,
            },
        ],
        structures: [
            {
                id: 1,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 1,
            },
            {
                id: 2,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 2,
            },
            {
                id: 3,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 3,
            },
            {
                id: 4,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 4,
            },
            {
                id: 5,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 5,
            },
            {
                id: 6,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 6,
            },
            {
                id: 7,
                type: SEAT_TYPE.EMPTY,
                row: 1,
                column: 7,
            },
            {
                id: 8,
                type: SEAT_TYPE.EMPTY,
                row: 1,
                column: 8,
            },
            {
                id: 9,
                type: SEAT_TYPE.EMPTY,
                row: 1,
                column: 9,
            },
            {
                id: 10,
                type: SEAT_TYPE.EMPTY,
                row: 1,
                column: 10,
            },
            {
                id: 11,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 11,
            },
            {
                id: 12,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 12,
            },
            {
                id: 13,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 13,
            },
            {
                id: 14,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 14,
            },
            {
                id: 15,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 15,
            },
            {
                id: 16,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 16,
            },
            {
                id: 17,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 1,
            },
            {
                id: 18,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 2,
            },
            {
                id: 19,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 3,
            },
            {
                id: 20,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 4,
            },
            {
                id: 21,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 5,
            },
            {
                id: 22,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 6,
            },
            {
                id: 23,
                type: SEAT_TYPE.EMPTY,
                row: 2,
                column: 7,
            },
            {
                id: 24,
                type: SEAT_TYPE.EMPTY,
                row: 2,
                column: 8,
            },
            {
                id: 25,
                type: SEAT_TYPE.EMPTY,
                row: 2,
                column: 9,
            },
            {
                id: 26,
                type: SEAT_TYPE.EMPTY,
                row: 2,
                column: 10,
            },
            {
                id: 27,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 11,
            },
            {
                id: 28,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 12,
            },
            {
                id: 29,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 13,
            },
            {
                id: 30,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 14,
            },
            {
                id: 31,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 15,
            },
            {
                id: 32,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 16,
            },
            {
                id: 33,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 1,
            },
            {
                id: 34,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 2,
            },
            {
                id: 35,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 3,
            },
            {
                id: 36,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 4,
            },
            {
                id: 37,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 5,
            },
            {
                id: 38,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 6,
            },
            {
                id: 39,
                type: SEAT_TYPE.EMPTY,
                row: 3,
                column: 7,
            },
            {
                id: 40,
                type: SEAT_TYPE.EMPTY,
                row: 3,
                column: 8,
            },
            {
                id: 41,
                type: SEAT_TYPE.EMPTY,
                row: 3,
                column: 9,
            },
            {
                id: 42,
                type: SEAT_TYPE.EMPTY,
                row: 3,
                column: 10,
            },
            {
                id: 43,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 11,
            },
            {
                id: 44,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 12,
            },
            {
                id: 45,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 13,
            },
            {
                id: 46,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 14,
            },
            {
                id: 47,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 15,
            },
            {
                id: 48,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 16,
            },
            {
                id: 49,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 1,
            },
            {
                id: 50,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 2,
            },
            {
                id: 51,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 3,
            },
            {
                id: 52,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 4,
            },
            {
                id: 53,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 5,
            },
            {
                id: 54,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 6,
            },
            {
                id: 55,
                type: SEAT_TYPE.EMPTY,
                row: 4,
                column: 7,
            },
            {
                id: 56,
                type: SEAT_TYPE.EMPTY,
                row: 4,
                column: 8,
            },
            {
                id: 57,
                type: SEAT_TYPE.EMPTY,
                row: 4,
                column: 9,
            },
            {
                id: 58,
                type: SEAT_TYPE.EMPTY,
                row: 4,
                column: 10,
            },
            {
                id: 59,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 11,
            },
            {
                id: 60,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 12,
            },
            {
                id: 61,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 13,
            },
            {
                id: 62,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 14,
            },
            {
                id: 63,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 15,
            },
            {
                id: 64,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 16,
            },
            {
                id: 65,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 1,
            },
            {
                id: 66,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 2,
            },
            {
                id: 67,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 3,
            },
            {
                id: 68,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 4,
            },
            {
                id: 69,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 5,
            },
            {
                id: 70,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 6,
            },
            {
                id: 71,
                type: SEAT_TYPE.EMPTY,
                row: 5,
                column: 7,
            },
            {
                id: 72,
                type: SEAT_TYPE.EMPTY,
                row: 5,
                column: 8,
            },
            {
                id: 73,
                type: SEAT_TYPE.EMPTY,
                row: 5,
                column: 9,
            },
            {
                id: 74,
                type: SEAT_TYPE.EMPTY,
                row: 5,
                column: 10,
            },
            {
                id: 75,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 11,
            },
            {
                id: 76,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 12,
            },
            {
                id: 77,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 13,
            },
            {
                id: 78,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 14,
            },
            {
                id: 79,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 15,
            },
            {
                id: 80,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 16,
            },
            {
                id: 81,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 1,
            },
            {
                id: 82,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 2,
            },
            {
                id: 83,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 3,
            },
            {
                id: 84,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 4,
            },
            {
                id: 85,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 5,
            },
            {
                id: 86,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 6,
            },
            {
                id: 87,
                type: SEAT_TYPE.EMPTY,
                row: 6,
                column: 7,
            },
            {
                id: 88,
                type: SEAT_TYPE.EMPTY,
                row: 6,
                column: 8,
            },
            {
                id: 89,
                type: SEAT_TYPE.EMPTY,
                row: 6,
                column: 9,
            },
            {
                id: 90,
                type: SEAT_TYPE.EMPTY,
                row: 6,
                column: 10,
            },
            {
                id: 91,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 11,
            },
            {
                id: 92,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 12,
            },
            {
                id: 93,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 13,
            },
            {
                id: 94,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 14,
            },
            {
                id: 95,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 15,
            },
            {
                id: 96,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 16,
            },
            {
                id: 97,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 1,
            },
            {
                id: 98,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 2,
            },
            {
                id: 99,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 3,
            },
            {
                id: 100,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 4,
            },
            {
                id: 101,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 5,
            },
            {
                id: 102,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 6,
            },
            {
                id: 103,
                type: SEAT_TYPE.EMPTY,
                row: 7,
                column: 7,
            },
            {
                id: 104,
                type: SEAT_TYPE.EMPTY,
                row: 7,
                column: 8,
            },
            {
                id: 105,
                type: SEAT_TYPE.EMPTY,
                row: 7,
                column: 9,
            },
            {
                id: 106,
                type: SEAT_TYPE.EMPTY,
                row: 7,
                column: 10,
            },
            {
                id: 107,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 11,
            },
            {
                id: 108,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 12,
            },
            {
                id: 109,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 13,
            },
            {
                id: 110,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 14,
            },
            {
                id: 111,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 15,
            },
            {
                id: 112,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 16,
            },
            {
                id: 113,
                type: SEAT_TYPE.DOUBLE,
                row: 8,
                column: 1,
            },
            {
                id: 115,
                type: SEAT_TYPE.DOUBLE,
                row: 8,
                column: 3,
            },
            {
                id: 117,
                type: SEAT_TYPE.DOUBLE,
                row: 8,
                column: 5,
            },
            {
                id: 119,
                type: SEAT_TYPE.EMPTY,
                row: 8,
                column: 7,
            },
            {
                id: 120,
                type: SEAT_TYPE.EMPTY,
                row: 8,
                column: 8,
            },
            {
                id: 121,
                type: SEAT_TYPE.EMPTY,
                row: 8,
                column: 9,
            },
            {
                id: 122,
                type: SEAT_TYPE.EMPTY,
                row: 8,
                column: 10,
            },
            {
                id: 123,
                type: SEAT_TYPE.DOUBLE,
                row: 8,
                column: 11,
            },

            {
                id: 125,
                type: SEAT_TYPE.DOUBLE,
                row: 8,
                column: 13,
            },
            {
                id: 127,
                type: SEAT_TYPE.DOUBLE,
                row: 8,
                column: 15,
            },
            {
                id: 129,
                type: SEAT_TYPE.DOUBLE,
                row: 9,
                column: 1,
            },
            {
                id: 130,
                type: SEAT_TYPE.DOUBLE,
                row: 9,
                column: 2,
            },
            {
                id: 131,
                type: SEAT_TYPE.DOUBLE,
                row: 9,
                column: 3,
            },
            {
                id: 132,
                type: SEAT_TYPE.EMPTY,
                row: 9,
                column: 4,
            },
            {
                id: 133,
                type: SEAT_TYPE.EMPTY,
                row: 9,
                column: 5,
            },
            {
                id: 134,
                type: SEAT_TYPE.EMPTY,
                row: 9,
                column: 6,
            },
            {
                id: 135,
                type: SEAT_TYPE.EMPTY,
                row: 9,
                column: 7,
            },
            {
                id: 136,
                type: SEAT_TYPE.DOUBLE,
                row: 9,
                column: 8,
            },
            {
                id: 138,
                type: SEAT_TYPE.DOUBLE,
                row: 9,
                column: 10,
            },
            {
                id: 140,
                type: SEAT_TYPE.DOUBLE,
                row: 9,
                column: 12,
            },
        ],
    },
    {
        id: 2,
        name: "A01",
        seatConfigs: [
            {
                type: SEAT_TYPE.NORMAL,
                price: PRICE.NORMAL,
            },
            {
                type: SEAT_TYPE.VIP,
                price: PRICE.VIP,
            },
            {
                type: SEAT_TYPE.DOUBLE,
                price: PRICE.DOUBLE,
            },
        ],
        structures: [
            {
                id: 1,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 1,
            },
            {
                id: 2,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 2,
            },
            {
                id: 3,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 3,
            },
            {
                id: 4,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 4,
            },
            {
                id: 5,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 5,
            },
            {
                id: 6,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 6,
            },
            {
                id: 7,
                type: SEAT_TYPE.EMPTY,
                row: 1,
                column: 7,
            },
            {
                id: 8,
                type: SEAT_TYPE.EMPTY,
                row: 1,
                column: 8,
            },
            {
                id: 9,
                type: SEAT_TYPE.EMPTY,
                row: 1,
                column: 9,
            },
            {
                id: 10,
                type: SEAT_TYPE.EMPTY,
                row: 1,
                column: 10,
            },
            {
                id: 11,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 11,
            },
            {
                id: 12,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 12,
            },
            {
                id: 13,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 13,
            },
            {
                id: 14,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 14,
            },
            {
                id: 15,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 15,
            },
            {
                id: 16,
                type: SEAT_TYPE.NORMAL,
                row: 1,
                column: 16,
            },
            {
                id: 17,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 1,
            },
            {
                id: 18,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 2,
            },
            {
                id: 19,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 3,
            },
            {
                id: 20,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 4,
            },
            {
                id: 21,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 5,
            },
            {
                id: 22,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 6,
            },
            {
                id: 23,
                type: SEAT_TYPE.EMPTY,
                row: 2,
                column: 7,
            },
            {
                id: 24,
                type: SEAT_TYPE.EMPTY,
                row: 2,
                column: 8,
            },
            {
                id: 25,
                type: SEAT_TYPE.EMPTY,
                row: 2,
                column: 9,
            },
            {
                id: 26,
                type: SEAT_TYPE.EMPTY,
                row: 2,
                column: 10,
            },
            {
                id: 27,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 11,
            },
            {
                id: 28,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 12,
            },
            {
                id: 29,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 13,
            },
            {
                id: 30,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 14,
            },
            {
                id: 31,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 15,
            },
            {
                id: 32,
                type: SEAT_TYPE.NORMAL,
                row: 2,
                column: 16,
            },
            {
                id: 33,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 1,
            },
            {
                id: 34,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 2,
            },
            {
                id: 35,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 3,
            },
            {
                id: 36,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 4,
            },
            {
                id: 37,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 5,
            },
            {
                id: 38,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 6,
            },
            {
                id: 39,
                type: SEAT_TYPE.EMPTY,
                row: 3,
                column: 7,
            },
            {
                id: 40,
                type: SEAT_TYPE.EMPTY,
                row: 3,
                column: 8,
            },
            {
                id: 41,
                type: SEAT_TYPE.EMPTY,
                row: 3,
                column: 9,
            },
            {
                id: 42,
                type: SEAT_TYPE.EMPTY,
                row: 3,
                column: 10,
            },
            {
                id: 43,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 11,
            },
            {
                id: 44,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 12,
            },
            {
                id: 45,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 13,
            },
            {
                id: 46,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 14,
            },
            {
                id: 47,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 15,
            },
            {
                id: 48,
                type: SEAT_TYPE.NORMAL,
                row: 3,
                column: 16,
            },
            {
                id: 49,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 1,
            },
            {
                id: 50,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 2,
            },
            {
                id: 51,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 3,
            },
            {
                id: 52,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 4,
            },
            {
                id: 53,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 5,
            },
            {
                id: 54,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 6,
            },
            {
                id: 55,
                type: SEAT_TYPE.EMPTY,
                row: 4,
                column: 7,
            },
            {
                id: 56,
                type: SEAT_TYPE.EMPTY,
                row: 4,
                column: 8,
            },
            {
                id: 57,
                type: SEAT_TYPE.EMPTY,
                row: 4,
                column: 9,
            },
            {
                id: 58,
                type: SEAT_TYPE.EMPTY,
                row: 4,
                column: 10,
            },
            {
                id: 59,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 11,
            },
            {
                id: 60,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 12,
            },
            {
                id: 61,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 13,
            },
            {
                id: 62,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 14,
            },
            {
                id: 63,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 15,
            },
            {
                id: 64,
                type: SEAT_TYPE.NORMAL,
                row: 4,
                column: 16,
            },
            {
                id: 65,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 1,
            },
            {
                id: 66,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 2,
            },
            {
                id: 67,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 3,
            },
            {
                id: 68,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 4,
            },
            {
                id: 69,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 5,
            },
            {
                id: 70,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 6,
            },
            {
                id: 71,
                type: SEAT_TYPE.EMPTY,
                row: 5,
                column: 7,
            },
            {
                id: 72,
                type: SEAT_TYPE.EMPTY,
                row: 5,
                column: 8,
            },
            {
                id: 73,
                type: SEAT_TYPE.EMPTY,
                row: 5,
                column: 9,
            },
            {
                id: 74,
                type: SEAT_TYPE.EMPTY,
                row: 5,
                column: 10,
            },
            {
                id: 75,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 11,
            },
            {
                id: 76,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 12,
            },
            {
                id: 77,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 13,
            },
            {
                id: 78,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 14,
            },
            {
                id: 79,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 15,
            },
            {
                id: 80,
                type: SEAT_TYPE.VIP,
                row: 5,
                column: 16,
            },
            {
                id: 81,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 1,
            },
            {
                id: 82,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 2,
            },
            {
                id: 83,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 3,
            },
            {
                id: 84,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 4,
            },
            {
                id: 85,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 5,
            },
            {
                id: 86,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 6,
            },
            {
                id: 87,
                type: SEAT_TYPE.EMPTY,
                row: 6,
                column: 7,
            },
            {
                id: 88,
                type: SEAT_TYPE.EMPTY,
                row: 6,
                column: 8,
            },
            {
                id: 89,
                type: SEAT_TYPE.EMPTY,
                row: 6,
                column: 9,
            },
            {
                id: 90,
                type: SEAT_TYPE.EMPTY,
                row: 6,
                column: 10,
            },
            {
                id: 91,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 11,
            },
            {
                id: 92,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 12,
            },
            {
                id: 93,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 13,
            },
            {
                id: 94,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 14,
            },
            {
                id: 95,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 15,
            },
            {
                id: 96,
                type: SEAT_TYPE.VIP,
                row: 6,
                column: 16,
            },
            {
                id: 97,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 1,
            },
            {
                id: 98,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 2,
            },
            {
                id: 99,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 3,
            },
            {
                id: 100,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 4,
            },
            {
                id: 101,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 5,
            },
            {
                id: 102,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 6,
            },
            {
                id: 103,
                type: SEAT_TYPE.EMPTY,
                row: 7,
                column: 7,
            },
            {
                id: 104,
                type: SEAT_TYPE.EMPTY,
                row: 7,
                column: 8,
            },
            {
                id: 105,
                type: SEAT_TYPE.EMPTY,
                row: 7,
                column: 9,
            },
            {
                id: 106,
                type: SEAT_TYPE.EMPTY,
                row: 7,
                column: 10,
            },
            {
                id: 107,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 11,
            },
            {
                id: 108,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 12,
            },
            {
                id: 109,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 13,
            },
            {
                id: 110,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 14,
            },
            {
                id: 111,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 15,
            },
            {
                id: 112,
                type: SEAT_TYPE.VIP,
                row: 7,
                column: 16,
            },
            {
                id: 113,
                type: SEAT_TYPE.DOUBLE,
                row: 8,
                column: 1,
            },
            {
                id: 115,
                type: SEAT_TYPE.DOUBLE,
                row: 8,
                column: 3,
            },
            {
                id: 117,
                type: SEAT_TYPE.DOUBLE,
                row: 8,
                column: 5,
            },
            {
                id: 119,
                type: SEAT_TYPE.EMPTY,
                row: 8,
                column: 7,
            },
            {
                id: 120,
                type: SEAT_TYPE.EMPTY,
                row: 8,
                column: 8,
            },
            {
                id: 121,
                type: SEAT_TYPE.EMPTY,
                row: 8,
                column: 9,
            },
            {
                id: 122,
                type: SEAT_TYPE.EMPTY,
                row: 8,
                column: 10,
            },
            {
                id: 123,
                type: SEAT_TYPE.DOUBLE,
                row: 8,
                column: 11,
            },

            {
                id: 125,
                type: SEAT_TYPE.DOUBLE,
                row: 8,
                column: 13,
            },
            {
                id: 127,
                type: SEAT_TYPE.DOUBLE,
                row: 8,
                column: 15,
            },
            {
                id: 129,
                type: SEAT_TYPE.DOUBLE,
                row: 9,
                column: 1,
            },
            {
                id: 130,
                type: SEAT_TYPE.DOUBLE,
                row: 9,
                column: 2,
            },
            {
                id: 131,
                type: SEAT_TYPE.DOUBLE,
                row: 9,
                column: 3,
            },
            {
                id: 132,
                type: SEAT_TYPE.EMPTY,
                row: 9,
                column: 4,
            },
            {
                id: 133,
                type: SEAT_TYPE.EMPTY,
                row: 9,
                column: 5,
            },
            {
                id: 134,
                type: SEAT_TYPE.EMPTY,
                row: 9,
                column: 6,
            },
            {
                id: 135,
                type: SEAT_TYPE.EMPTY,
                row: 9,
                column: 7,
            },
            {
                id: 136,
                type: SEAT_TYPE.DOUBLE,
                row: 9,
                column: 8,
            },
            {
                id: 138,
                type: SEAT_TYPE.DOUBLE,
                row: 9,
                column: 10,
            },
            {
                id: 140,
                type: SEAT_TYPE.DOUBLE,
                row: 9,
                column: 12,
            },
        ],
    },
];
